### PR TITLE
The tutorial previously defined `ht_hash`, but not `ht_generic_hash`

### PR DESCRIPTION
**Pull request by freefal**

### CODE REVIEW

**Comment by olishmollie** [comment]
@freefal I could be massively misunderstanding everything here (novice C programmer), but in the `insert`, `search`, etc. methods the author seems to call `ht_hash` with the args of `ht_get_hash`, which makes it insufficient to simply change `ht_generic_hash` to `ht_hash`. You'd then be skipping the open addressing step (by calling the generic `ht_hash` in all interface methods).

A better solution might be to first define `ht_hash`, then once open addressing was explained/implemented change `ht_hash` to `ht_generic_hash`, and then either call `ht_get_hash` in all interface methods or change `ht_get_hash` to `ht_hash`.

Like I said, I could be way off, so please to don't hesitate to tell me so.

**Comment by freefal** [comment]
@olishmollie I'm not 100% sure either, but I think the calls from `insert,
search, etc.` should be using `ht_get_hash`, which in turn should be
calling `ht_hash`

**Comment by olishmollie** [comment]
@freefal, yeah I think that's best. Too much renaming would get confusing.

**Comment by jamesroutley** [comment]
@freefal @olishmollie - you guys are absolutely correct - thanks for taking the time to fix this!

**Pull request merged**
