### PR TITLE
Fixed logical flaw concerning HT_DELETED_ITEM handling

### PR DESCRIPTION
**Pull request by badagent**
Great tutorial, but I think I found a logical flaw.

I might be wrong, but imho testing for HT_DELETED_ITEM in the Header of the while loop leads to errors in  the Hash Chain.
Elements that previously collided with the deleted element will not be found anymore as the while loop terminates before finding that element.

### CODE REVIEW

**Comment by jamesroutley** [comment]
Hi @badagent - yep, you're correct about the error. I'm happy to merge this, but could you edit the formatting of the new code to match the existing? Also it looks like there's also a merge conflict. `ht_hash` has been changed to `ht_get_hash` - would you mind updating it in your code? Let me know if you need a hand with any of this - I'm happy to help. Thanks!

**Comment by badagent** [comment]
Hi @jamesroutley sorry about the formatting. I replaced my TABs with 4 spaces and added a space between my 'if' and the '('.

The conflict was indeed resolved by renaming ht_hash to ht_get_hash and chaging the link to the next page.

Hope you can merge it now, thanks for providing a great tutorial :)

**Comment by jamesroutley** [comment]
Hi @badagent thanks for updating it. I've just spotted another formatting thing - could we add spaces around the not equal operator:

`item!=&HT_DELETED_ITEM` -> `item != &HT_DELETED_ITEM` for each of the three comparisons?

Thanks!

**Comment by jamesroutley** [comment]
Fab - thanks again @badagent!

**Pull request merged**
